plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    alias libs.plugins.publishing
}

repositories {
    maven { url 'https://jitpack.io' }
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}


dependencies {
    modImplementation(libs.fabric.loader)
    modApi(libs.fabric.api)
    modApi(libs.pehkui.fabric) {
        exclude group: "net.fabricmc.fabric-api"
    }
    modImplementation include(libs.midnightlib.fabric.get())

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

//var mod = createModReleaseMetadata(
//        "Size Shifting Potions v${project.version} Fabric",
//        file("$rootDir/CHANGELOG.md"),
//        ["1.20.1"],
//        ["fabric", "quilt"],
//        "remapJar",
//        ["remapSourcesJar"],
//        "v${project.version}-fabric",
//        false
//)
//modrinthInfo(mod, "sizeshiftingpotions", ["pehkui"], [], [], ["midnightlib"])
//githubInfo(mod, "UltrusBot", "SizeShiftingPotions", "1.20")
//curseforgeInfo(mod, TaskPublishCurseForge, "447440", ["midnightlib"], ["pehkui"])

publishMods {
    displayName = "Size Shifting Potions v${project.version} Fabric"
    file = remapJar.archiveFile
    changelog = file("$rootDir/CHANGELOG.md").text
    version = "v${project.version}-fabric"
    type = STABLE
    modLoaders.addAll("fabric", "quilt")
    curseforge {
        projectId = "447440"
        minecraftVersions.add("1.20.1")
        accessToken = providers.gradleProperty("CF_API_KEY")
        embeds {
            slug = "midnightlib"
        }
        requires {
            slug = "pehkui"
        }
    }
    modrinth {
        projectId = "rfj2v0X6"
        minecraftVersions.add("1.20.1")
        accessToken = providers.gradleProperty("MODRINTH_TOKEN")
        embeds {
            slug = "midnightlib"
        }
        requires {
            slug = "pehkui"
        }
    }
    github {
        repository = "UltrusBot/SizeShiftingPotions"
        commitish = "1.20"
        accessToken = providers.gradleProperty("GH_TOKEN")
        tagName = "v$project.version-fabric"
    }

    dryRun = false
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    classifier "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    classifier null
    archiveClassifier = "fabric"
}

jar {
    classifier "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
